user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@UserBundle/Controller/AdminController.php"
   # resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

    
   