<?php

namespace EENE\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PivotFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PivotFileRepository extends EntityRepository
{
}
